Fix incorrect backticks in validation

diff --git a/server/scripts/__validation b/server/scripts/__validation
--- a/server/scripts/__validation
+++ b/server/scripts/__validation
@@ -5,7 +5,7 @@ source __lookup
 validate_login() {
     local login="$1"
     if ! [[ $login =~ [A-Za-z0-9_.-]+ ]]; then
-        printf '%s: Invalid login: `login=%s`' "$0" "$login" >&2
+        printf '%s: Invalid login: login=`%s`' "$0" "$login" >&2
         false
     fi
 }
@@ -13,7 +13,7 @@ validate_login() {
 validate_repo_name() {
     local repo="$1"
     if ! ( grep -qE '^([[:alnum:]]|[ _.-])+$' <<< "$repo" ); then
-        printf '%s: Invalid repo name: `repo=%s`' "$0" "$repo" >&2
+        printf '%s: Invalid repo name: repo=`%s`' "$0" "$repo" >&2
         false
     fi
 }
@@ -21,7 +21,7 @@ validate_repo_name() {
 check_user_exists() {
     local login="$1"
     if ! user_exists $login; then
-        printf '%s: User does not exist: `login=%s`' "$0" "$login" >&2
+        printf '%s: User does not exist: login=`%s`' "$0" "$login" >&2
         false
     fi
 }
@@ -29,7 +29,7 @@ check_user_exists() {
 check_user_not_exists() {
     local login="$1"
     if user_exists $login; then
-        printf '%s: User exists: `login=%s`' "$0" "$login" >&2
+        printf '%s: User exists: login=`%s`' "$0" "$login" >&2
         false
     fi
 }
@@ -39,7 +39,7 @@ check_is_admin() {
 
     local role=$(get_role $login)
     if [[ $role != admin ]]; then
-        printf '%s: Not an admin: `login=%s`' "$0" "$login" >&2
+        printf '%s: Not an admin: login=`%s`' "$0" "$login" >&2
         false
     fi
 }
@@ -49,7 +49,7 @@ check_not_admin() {
 
     local role=$(get_role $login)
     if [[ $role == admin ]]; then
-        printf '%s: Is admin: `login=%s`' "$0" "$login" >&2
+        printf '%s: Is admin: login=`%s`' "$0" "$login" >&2
         false
     fi
 }
@@ -59,7 +59,7 @@ check_repo_exists() {
 
     #if [ ! -d "$REPO_DIR"/"$repo" ]; then
     if ! repo_exists "$repo"; then
-        printf '%s: Repo does not exist: `repo=%s`' "$0" "$repo" >&2
+        printf '%s: Repo does not exist: repo=`%s`' "$0" "$repo" >&2
         false
     fi
 }
@@ -68,7 +68,7 @@ check_no_repo() {
     local repo="$1"
 
     if repo_exists "$repo"; then
-        printf '%s: Repo exists: `repo=%s`' "$0" "$repo" >&2
+        printf '%s: Repo exists: repo=`%s`' "$0" "$repo" >&2
         false
     fi
 }
